Repository be14-2nd-spring-is-coming/be14-3rd-springiscomming-marktory-FE, pull requests merged in 2025-04, with the labels that each got.

#1 [FEAT] web 전체 테마 색상,
  src/App.vue
  src/assets/post/content-img.png
  src/components/Post.vue
  src/components/post/Category.vue
  src/components/post/Post.vue
  src/pages/ArticlePage.vue
  vite.config.js
Labels: ✨ Feat

#4 [FEAT] 공통 헤더 구현 완료
  src/assets/icons/marktory-logo-gray.svg
  src/assets/icons/marktory-logo.svg
  src/components/footer/AppFooter.vue
  src/components/footer/SideFooter.vue
  src/pages/HomePage.vue
Labels: ✨ Feat

#5 [FEAT] Header 구현 완료
  src/assets/icons/chervon-down.svg
  src/assets/icons/notification.svg
  src/assets/icons/search.svg
  src/components/AppHeader.vue
  src/pages/HomePage.vue
Labels: ✨ Feat

#7 [FEAT] Login + member.json 연동 완료
  package.json
  public/marktory_cat.png
  public/marktory_logo.png
  server/member-clean.json
  src/App.vue
  src/components/login/InputField.vue
  src/components/login/LoginButton.vue
  src/components/login/eye-closed.svg
  src/components/login/eye-open.svg
  src/pages/FindIdPage.vue
  src/pages/LoginPage.vue
  src/router/index.js
Labels: ✨ Feat

#9 [REFACTOR] Login Page 내에 Header, Footer 추가
  src/App.vue
  src/assets/icons/marktory-cat.svg
  src/pages/FindIdPage.vue
  src/pages/LoginPage.vue
Labels: 🔧 Refactor

#11 [FEAT] Mypage 화면 구성, 프로필 컴포넌트 구현
  src/assets/icons/follow-icon.svg
  src/components/mypage/PostCard.vue
  src/components/mypage/PostCardList.vue
  src/components/mypage/SideProfile.vue
  src/components/mypage/TempCardList.vue
  src/pages/MyPage.vue
  src/router/index.js
Labels: ✨ Feat

#12 [FEAT] AppHeader 로그인 상태(임시), 드롭다운 구현 완료
  package-lock.json
  package.json
  src/assets/icons/activity.svg
  src/assets/icons/logout.svg
  src/assets/icons/notice.svg
  src/assets/icons/pochaco.png
  src/assets/icons/settings.svg
  src/components/AppHeader.vue
  src/pages/HomePage.vue
Labels: ✨ Feat

#13 [Refactor] Footer 리팩토링 완료
  src/components/footer/AppFooter.vue
  src/components/footer/SideFooter.vue
  src/router/index.js
Labels: 🔧 Refactor

#15 [FEAT] 에디터 UI
  .gitignore
  package-lock.json
  package.json
  src/assets/post/arrow.svg
  src/assets/post/check-empty.svg
  src/assets/post/check-fill.svg
  src/components/post/MarkdownEditor.vue
  src/components/post/MarkdownViewer.vue
  src/components/post/PublishBottomSheet.vue
  src/main.js
  src/pages/ArticlePage.vue
  src/pages/EditorPage.vue
  src/router/index.js
Labels: ⚙ Chore, ✨ Feat, 🔧 Refactor

#21 [FEAT] 마이페이지 json 서버 연동
  public/default-img.png
  server/mypage/mypage.json
  src/assets/icons/comment-icon.svg
  src/assets/icons/download-icon.svg
  src/assets/icons/heart-icon.svg
  src/components/mypage/D_profile_IMG.png
  src/components/mypage/PostCard.vue
  src/components/mypage/PostCardList.vue
  src/components/mypage/SideProfile.vue
  src/components/mypage/TempCardList.vue
  src/components/mypage/default-img.png
  src/pages/MyPage.vue
Labels: ✨ Feat

#19 [FEAT] 아이디 찾기 UI 구현
  package.json
  src/pages/FindIdPage.vue
Labels: ✨ Feat

#22 [FEAT] 아이디 찾기 결과 페이지 구현
  server/login/login-test.json
  src/pages/FindIdPage.vue
  src/pages/FindIdResultPage.vue
  src/router/index.js
Labels: ✨ Feat

#23 [FEAT] 인라인 태그 UI및 입력, 삭제
  src/components/post/MarkdownEditor.vue
  src/components/post/MarkdownViewer.vue
  src/pages/EditorPage.vue
Labels: ✨ Feat, 🔨 Fix

#24 [FEAT] 회원가입 후 환영 페이지 구현
  public/marktory_cat.png
  public/marktory_logo.png
  src/pages/FindIdPage.vue
  src/pages/LoginPage.vue
  src/pages/PreSignupPage.vue
  src/pages/SignupPage.vue
  src/pages/SignupResultPage.vue
  src/router/index.js
Labels: ⚙ Chore, ✨ Feat

#25 [REFACTOR] 이미지 assets 변경, @ 적용
  src/assets/icons/eye-closed.svg
  src/assets/icons/eye-open.svg
  src/components/login/InputField.vue
  src/pages/FindIdPage.vue
  src/pages/FindIdResultPage.vue
  src/pages/LoginPage.vue
  src/pages/PreSignupPage.vue
  src/pages/SignupPage.vue
Labels: ⚙ Chore, 🔧 Refactor

#29 [FEAT] 관리자페이지 메인 및 공지사항관리 구현
  src/components/admin/AdminPagination.vue
  src/components/admin/AdminSidebar.vue
  src/components/admin/NoticeAdmin.vue
  src/pages/AdminPage.vue
  src/router/index.js
Labels: ✨ Feat

#30 [FEAT] 설정페이지 화면 구성, 설정페이지 컴포넌트 구현
  src/assets/icons/doeun-profile.svg
  src/components/setting/setting.vue
  src/pages/SettingPage.vue
  src/router/index.js
Labels: ✨ Feat

#34 [FEAT] 카테고리 관리 페이지 구현
  src/assets/icons/check-icon-orange.svg
  src/assets/icons/check-icon-white.svg
  src/assets/icons/edit-icon-orange.svg
  src/assets/icons/edit-icon-white.svg
  src/assets/icons/trash-icon-orange.svg
  src/assets/icons/trash-icon-white.svg
  src/components/AppHeader.vue
  src/components/category/CategoryItem.vue
  src/pages/CategoryPage.vue
  src/pages/MyPage.vue
  src/router/index.js
Labels: ✨ Feat

#36 [FIX] 아이디 찾기 오류 해결
  src/pages/FindIdPage.vue
Labels: 🔨 Fix

#39 [FEAT] pinia import를 통한, 로그인 상태와 로그아웃 상태 구현 완료 및 헤더의 회원 정보 불러오기 성공
  package-lock.json
  package.json
  src/assets/icons/defaultProfile.png
  src/components/AppHeader.vue
  src/main.js
  src/pages/LoginPage.vue
  src/stores/memberStore.js
Labels: ✨ Feat

#41 [REFACTOR] sidefooter 축소 시 화면 표시, footer 수정
  src/App.vue
  src/components/footer/AppFooter.vue
  src/components/footer/SideFooter.vue
Labels: ✨ Feat, 🔨 Fix, 🔧 Refactor

#44 [FEAT] 댓글 UI
  src/assets/comment/alex_profile.png
  src/assets/comment/d_profile.png
  src/assets/comment/dong_profile.png
  src/assets/comment/kassy_profile.png
  src/assets/comment/morris_profile.png
  src/assets/comment/tim_profile.png
  src/assets/icons/heart-icon-empty.svg
  src/assets/icons/reply-icon.svg
  src/components/comment/Comment.vue
  src/components/comment/CommentInput.vue
  src/components/comment/CommentItem.vue
  src/components/comment/CommentList.vue
  src/components/comment/ReplyItem.vue
  src/pages/ArticlePage.vue
Labels: ✨ Feat

#45 [REFACTOR] header 비율 수정에 따른 UI 비율 수정 (상세내역 참고)
  src/pages/FindIdPage.vue
  src/pages/FindIdResultPage.vue
  src/pages/FindPwPage.vue
  src/pages/LoginPage.vue
  src/pages/PreFindPwPage.vue
  src/pages/PreSignupPage.vue
  src/pages/SignupPage.vue
  src/pages/SignupResultPage.vue
Labels: 🔧 Refactor

#46 [FEAT] 비밀번호 변경 이메일 전송 및 목업 데이터 비밀번호 변경 완료
  server/login/login-test.json
  src/pages/FindPwPage.vue
  src/pages/SignupPage.vue
Labels: ✨ Feat

#48 [FEATURE] 공지사항 게시글 관리 UI구현 및 json설정
  server/admin/notices.json
  src/components/admin/NoticeAdmin.vue
  src/components/admin/NoticeContentPage.vue
  src/components/admin/NoticeEditModal.vue
  src/components/admin/NoticeInsert.vue
Labels: ✨ Feat

#52 [FEAT] 설정 페이지 구현
  src/assets/icons/default-profile.svg
  src/components/setting/ConfirmWithdrawal.vue
  src/components/setting/WithdrawalEnd.vue
  src/components/setting/WithdrawalInput.vue
  src/components/setting/setting.vue
Labels: ✨ Feat

#53 [REFACTOR] 공지사항 구현 UI index설정 및 style수정
  src/components/admin/AdminPagination.vue
  src/components/admin/AdminSidebar.vue
  src/components/admin/NoticeAdmin.vue
  src/components/admin/NoticeContentPage.vue
  src/pages/AdminPage.vue
  src/router/index.js
Labels: 🔧 Refactor

#55 [REFACTOR] 헤더 변경에 따른 페이지 margin 수정
  src/pages/ActivityPage.vue
  src/pages/CategoryPage.vue
  src/pages/MyPage.vue
Labels: 🔧 Refactor

#57 [FEAT] 메인 페이지 모달 창 구현 완료
  src/components/ArrayModal.vue
  src/pages/HomePage.vue
Labels: ✨ Feat

#59 [FEAT] 팔로잉, 팔로워 모달 구현
  src/components/follow/FollowUser.vue
  src/components/follow/FollowUserList.vue
  src/components/mypage/SideProfile.vue
Labels: ✨ Feat

#61 [FEAT] HomePage 구현
  src/App.vue
  src/components/AppHeader.vue
  src/components/footer/SideFooter.vue
  src/components/mypage/PostCardList.vue
  src/components/mypage/TempCardList.vue
  src/pages/HomePage.vue
  src/router/index.js
Labels: ✨ Feat, 🔨 Fix, 🎨 Style

#69 [FEAT] 관리자일 때 달라지는 드롭다운 구현 완료
  src/assets/icons/admin-key.svg
  src/components/AppHeader.vue
Labels: ✨ Feat

#72 [FEAT] 게시물 작성
  src/api/hashtag.api.js
  src/api/post.api.js
  src/api/template.api.js
  src/components/comment/Comment.vue
  src/components/comment/CommentItem.vue
  src/components/comment/ReplyItem.vue
  src/components/post/Category.vue
  src/components/post/Post.vue
  src/models/authority.js
  src/models/category.js
  src/models/comment.js
  src/models/email-token.js
  src/models/hashtag.js
  src/models/like.js
  src/models/member-roles.js
  src/models/member-template.js
  src/models/member.js
  src/models/notice.js
  src/models/post-hashtag.js
  src/models/post.js
  src/models/public-template.js
  src/models/subscribe.js
  src/models/template-space.js
  src/pages/ArticlePage.vue
  src/pages/EditorPage.vue
  src/utils/format-data.js
Labels: ✨ Feat

#74 [Refactor] 이메일 인증 예외처리 테스트 및 코드 수정 완료
  server/mypage/mypage.json
  src/pages/PreSignupPage.vue
  src/pages/SignupPage.vue
Labels: 🔧 Refactor

#77 [REFACTOR] 헤더 수정 및 API 경로 수정
  src/assets/icons/category.svg
  src/components/follow/FollowUser.vue
  src/components/mypage/KaseyPostCardList.vue
  src/components/post/Category.vue
  src/pages/ActivityPage.vue
  src/pages/CategoryPage.vue
  src/pages/MyPage.vue
  src/pages/OtherMyPage.vue
Labels: 🔧 Refactor

#78 [FEAT] 댓글 등록
  src/api/like.api.js
  src/components/comment/Comment.vue
  src/components/comment/CommentItem.vue
  src/components/comment/CommentList.vue
  src/pages/ArticlePage.vue
Labels: ✨ Feat

#81 [FEAT] 설정페이지 구현
  src/components/setting/ImageDelete.vue
  src/components/setting/setting.vue
  src/pages/SettingPage.vue
Labels: ✨ Feat

#82 [FEAT] 메인 화면 필요한 모달창 구현, 좋아요순, 사용순 정렬 완료, 비로그인 창 구독 클릭 시 로그인 창으로
  src/components/PageModal.vue
  src/components/TemplateModal.vue
  src/components/mypage/PostCardList.vue
  src/components/mypage/TempCardList.vue
  src/pages/HomePage.vue
Labels: ✨ Feat

#87 [FEATURE] 관리자페이지 회원관리 ui 구현
  server/mypage/mypage.json
  src/components/admin/AdminSidebar.vue
  src/components/admin/MemberAdmin.vue
  src/components/admin/NoticeAdmin.vue
  src/components/admin/ReportAdmin.vue
  src/router/index.js
Labels: ✨ Feat

#83 style : 기본 프로필
  src/components/comment/CommentItem.vue
Labels: ✨ Feat

#91 [Refactor] 발표 때 했던 버전으로 최신화
  server/mypage/mypage.json
  src/components/AppHeader.vue
  src/components/admin/MemberAdmin.vue
  src/components/admin/NoticeAdmin.vue
  src/components/admin/ReportAdmin.vue
  src/pages/MyPage.vue
  src/pages/OtherMyPage.vue
  src/pages/SignupPage.vue
Labels: ✨ Feat, 🔧 Refactor

#92 [DOCS] 와이어프레임, 스토리보드 업로드
  image/스토리보드/게시글신고_스토리보드.png
  image/스토리보드/관리자로그인_스토리보드.png
  image/스토리보드/닉네임수정_스토리보드.png
  image/스토리보드/댓글신고_스토리보드.png
  image/스토리보드/로그아웃_스토리보드.png
  image/스토리보드/로그인_스토리보드.png
  image/스토리보드/비밀번호수정_스토리보드.png
  image/스토리보드/비밀번호찾기_스토리보드.png
  image/스토리보드/신고내역조회_스토리보드.png
  image/스토리보드/신고처리_스토리보드.png
  image/스토리보드/아이디찾기_스토리보드.png
  image/스토리보드/약관동의_스토리보드.png
  image/스토리보드/전체회원조회_스토리보드.png
  image/스토리보드/프로필이미지수정_스토리보드.png
  image/스토리보드/회원가입_스토리보드.png
  image/스토리보드/회원계정상태변경_스토리보드.png
  image/스토리보드/회원탈퇴_스토리보드.png
  image/와이어프레임/게시글신고_와이어프레임.png
  image/와이어프레임/관리자로그인_와이어프레임.png
  image/와이어프레임/닉네임수정_와이어프레임.png
  image/와이어프레임/댓글신고_와이어프레임.png
  image/와이어프레임/로그아웃_와이어프레임.png
  image/와이어프레임/로그인_와이어프레임.png
  image/와이어프레임/비밀번호수정_와이어프레임.png
  image/와이어프레임/비밀번호찾기_와이어프레임.png
  image/와이어프레임/신고내역조회_와이어프레임.png
  image/와이어프레임/신고처리_와이어프레임.png
  image/와이어프레임/아이디찾기_와이어프레임.png
  image/와이어프레임/약관동의_와이어프레임.png
  image/와이어프레임/전체회원조회_와이어프레임.png
  image/와이어프레임/프로필이미지수정_와이어프레임.png
  image/와이어프레임/회원가입_와이어프레임.png
  image/와이어프레임/회원계정상태변경_와이어프레임.png
  image/와이어프레임/회원탈퇴_와이어프레임.png
Labels: 📃 Docs

#93 [DOCS] README 이미지 추가
  image/스토리보드/내가남긴댓글조회_스토리보드.png
  image/스토리보드/댓글좋아요_스토리보드.png
  image/스토리보드/댓글좋아요취소_스토리보드.png
  image/스토리보드/본인게시글조회_스토리보드.png
  image/스토리보드/본인템플릿조회_스토리보드.png
  image/스토리보드/좋아요누른게시글조회_스토리보드.png
  image/스토리보드/좋아요누른댓글조회_스토리보드.png
  image/스토리보드/카테고리등록_스토리보드.png
  image/스토리보드/카테고리삭제_스토리보드.png
  image/스토리보드/카테고리수정_스토리보드.png
  image/스토리보드/카테고리조회_스토리보드.png
  image/스토리보드/타회원게시글조회_스토리보드.png
  image/스토리보드/타회원템플릿조회_스토리보드.png
  image/스토리보드/템플릿삭제_스토리보드.png
  image/스토리보드/템플릿수정_스토리보드.png
  image/스토리보드/템플릿작성_스토리보드.png
  image/스토리보드/템플릿조회_스토리보드.png
  image/와이어프레임/내가남긴댓글조회_와이어프레임.png
  image/와이어프레임/댓글좋아요_와이어프레임.png
  image/와이어프레임/댓글좋아요취소_와이어프레임.png
  image/와이어프레임/본인게시글조회_와이어프레임.png
  image/와이어프레임/본인템플릿조회_와이어프레임.png
  image/와이어프레임/좋아요누른게시글조회_와이어프레임.png
  image/와이어프레임/좋아요누른댓글조회_와이어프레임.png
  image/와이어프레임/카테고리등록_와이어프레임.png
  image/와이어프레임/카테고리삭제_와이어프레임.png
  image/와이어프레임/카테고리수정_와이어프레임.png
  image/와이어프레임/카테고리조회_와이어프레임.png
  image/와이어프레임/타회원게시글조회_와이어프레임.png
  image/와이어프레임/타회원템플릿조회_와이어프레임.png
  image/와이어프레임/템플릿삭제_와이어프레임.png
  image/와이어프레임/템플릿수정_와이어프레임.png
  image/와이어프레임/템플릿작성_와이어프레임.png
  image/와이어프레임/템플릿조회_와이어프레임.png
Labels: 📃 Docs

#96 [DOCS] 와이어프레임, 스토리보드 사진 추가
  image/스토리보드/게시글공개범위설정_스토리보드.png
  image/스토리보드/게시글삭제_스토리보드.png
  image/스토리보드/게시글수정_스토리보드.png
  image/스토리보드/게시글작성_스토리보드.png
  image/스토리보드/게시글조회_스토리보드.png
  image/스토리보드/게시글좋아요_스토리보드.png
  image/스토리보드/게시글카테고리적용_스토리보드.png
  image/스토리보드/게시글해시태그등록_스토리보드.png
  image/스토리보드/게시글해시태그삭제_스토리보드.png
  image/스토리보드/템플릿선택_스토리보드.png
  image/와이어프레임/게시글공개범위설정_와이어프레임.png
  image/와이어프레임/게시글삭제_와이어프레임.png
  image/와이어프레임/게시글수정_와이어프레임.png
  image/와이어프레임/게시글작성_와이어프레임.png
  image/와이어프레임/게시글조회_와이어프레임.png
  image/와이어프레임/게시글좋아요_와이어프레임.png
  image/와이어프레임/게시글카테고리적용_와이어프레임.png
  image/와이어프레임/게시글해시태그등록_와이어프레임.png
  image/와이어프레임/게시글해시태그삭제_와이어프레임.png
  image/와이어프레임/템플릿선택_와이어프레임.png
Labels: 📃 Docs

#95 [DOCS] readme 이미지 추가
  image/스토리보드/공지사항삭제_스토리보드.png
  image/스토리보드/공지사항수정_스토리보드.png
  image/스토리보드/공지사항작성_스토리보드.png
  image/스토리보드/공지사항조회_스토리보드.png
  image/스토리보드/구독알림_스토리보드.png
  image/스토리보드/구독추가_스토리보드.png
  image/스토리보드/구독취소_스토리보드.png
  image/스토리보드/대댓글등록_스토리보드.png
  image/스토리보드/대댓글삭제_스토리보드.png
  image/스토리보드/대댓글수정_스토리보드.png
  image/스토리보드/대댓글조회_스토리보드.png
  image/스토리보드/댓글등록_스토리보드.png
  image/스토리보드/댓글삭제_스토리보드.png
  image/스토리보드/댓글수정_스토리보드.png
  image/스토리보드/댓글조회_스토리보드.png
  image/스토리보드/본인을구독한목록 조회_스토리보드.png
  image/스토리보드/본인이구독한목록조회_스토리보드.png
  image/와이어프레임/공지사항삭제_와이어프레임.png
  image/와이어프레임/공지사항수정_와이어프레임.png
  image/와이어프레임/공지사항작성_와이어프레임.png
  image/와이어프레임/공지사항조회_와이어프레임.png
  image/와이어프레임/구독알림_와이어프레임.png
  image/와이어프레임/구독추가_와이어프레임.png
  image/와이어프레임/구독취소_와이어프레임.png
  image/와이어프레임/대댓글등록_와이어프레임.png
  image/와이어프레임/대댓글삭제_와이어프레임.png
  image/와이어프레임/대댓글수정_와이어프레임.png
  image/와이어프레임/대댓글조회_와이어프레임.png
  image/와이어프레임/댓글등록_와이어프레임.png
  image/와이어프레임/댓글삭제_와이어프레임.png
  image/와이어프레임/댓글수정_와이어프레임.png
  image/와이어프레임/댓글조회_와이어프레임.png
  image/와이어프레임/본인을구독한목록 조회_와이어프레임.png
  image/와이어프레임/본인이구독한목록조회_와이어프레임.png
Labels: 📃 Docs
